const sampleListings = [
  {
    title: " Mountain Lodge Retreat ",
    description:"  A cozy, luxury lodge nestled in the heart of the Alps. Perfect for skiing and winter sports.",
    image: {
      filename:"Image",
      url: " https://www.livelikeitstheweekend.com/wp-content/uploads/2017/11/Staying-at-Buffalo-Mountain-Lodge-Banff-Alberta-Canada-1-of-1.webp ",
    },
    price: 12000 ,
    location: "Alps ",
    country: "Switzerland ",
    categories:'Mountains',
  },
  {
    title: " Himalayan Adventure Resort",
    description:" Enjoy breathtaking views of the Himalayas in this eco-friendly resort. ",
    image: {
      filename:"Image",
      url: "  https://cdn.onekindesign.com/wp-content/uploads/2019/05/Rustic-Home-Design-Locati-Architects-01-1-Kindesign.jpg",
    },
    price:  15500,
    location: " Himalayas",
    country: "Nepal ",
    categories:'Mountains',
  }, {
    title: "  Rocky Mountain Cabins",
    description:"  Private cabins in the Rocky Mountains with spectacular views and outdoor activities.",
    image: {
      filename:"Image",
      url: "  https://media.istockphoto.com/id/471775841/photo/wood-cottage-with-a-beautiful-forest-and-mountain-views.jpg?s=612x612&w=0&k=20&c=Oipo8maY4FHjvCMVEbeAXAmTyyonIM-oqc6rTh24jN0=",
    },
    price:10500 ,
    location: " Rockies",
    country: "USA ",
    categories:'Mountains',
  }, {
    title: " Andes Mountain Hideaway",
    description:"  A remote hideaway in the Andes offering adventure and tranquility.",
    image: {
      filename:"Image",
      url: " https://api.lakewanaka.co.nz/assets/Uploads/ImportedImages/Studio-small5__FocusFillWzE5MjAsMTA4MCwieSIsMTAwXQ.jpg ",
    },
    price:  13000,
    location: "Andes ",
    country: "Chile ",
    categories:'Mountains',
  }, {
    title: "Pyrenees Mountain Escape ",
    description:"An exclusive escape in the Pyrenees, perfect for hiking and nature lovers.",
    image: {
      filename:"Image",
      url: "https://api.lakewanaka.co.nz/assets/Uploads/ImportedImages/Studio-Small10-v2__FocusFillWzE5MjAsMTA4MCwieSIsNzZd.jpg  ",
    },
    price:1000 ,
    location: " Pyrenees",
    country: " France",
    categories:'Mountains',
  }, {
    title: "Dolomites Ski Resort ",
    description:"Ski-in/ski-out resort in the Dolomites with world-class dining and spa. ",
    image: {
      filename:"Image",
      url: " https://api.lakewanaka.co.nz/assets/Uploads/ImportedImages/Studio-small10__FocusFillWzE5MjAsMTA4MCwieSIsMTAwXQ.jpg ",
    },
    price: 18000,
    location: "Dolomites ",
    country: " Italy",
    categories:'Mountains',
  }, {
    title: " Japanese Alps Resort",
    description:" A traditional ryokan in the Japanese Alps with hot springs and serene landscapes. ",
    image: {
      filename:"Image",
      url: "https://skiasia.com/wp-content/uploads/2023/12/KijimadairaSkiInOutLodgeWinter.jpeg ",
    },
    price: 19000  ,
    location: " Nagano",
    country: " Japan",
    categories:'Mountains',
  }, {
    title: "Canadian Rockies Retreat ",
    description:" Luxury retreat in the heart of the Canadian Rockies, ideal for wilderness adventures.",
    image: {
      filename:"Image",
      url: " https://skiasia.com/wp-content/uploads/2023/12/0-ADDRESS-NAGASAKA-4.jpg ",
    },
    price:  17000,
    location: "Banff ",
    country: "Canada ",
    categories:'Mountains',
  }, {
    title: "Atlas Mountains Eco-Lodge ",
    description:" An eco-friendly lodge in the Atlas Mountains offering cultural experiences. ",
    image: {
      filename:"Image",
      url: " https://casualtravelist.com/wp-content/uploads/2018/01/20171002_165318.jpg ",
    },
    price: 9500 ,
    location: "  Atlas Mountains",
    country: "Morocco ",
    categories:'Mountains',
  }, {
    title: "Oceanfront Pool Paradise ",
    description:" A beachfront resort featuring infinity pools overlooking the sea. ",
    image: {
      filename:"Image",
      url: "  https://static.wixstatic.com/media/6a6fac_aa0d72c08682420a81642166d7eebebb~mv2.jpg/v1/fill/w_734,h_751,al_c,q_85,enc_auto/6a6fac_aa0d72c08682420a81642166d7eebebb~mv2.jpg",
    },
    price: 25000,
    location: " Maldives",
    country: "Maldives ",
    categories:'Pools',
  },
  {
    title: " Luxury Pool Villas ",
    description:" Private pool villas in the tropical paradise of Bali, perfect for a romantic getaway.",
    image: {
      filename:"Image",
      url: " https://content.phuket101.net/wp-content/uploads/20170609222130/trisara-villas.jpg",
    },
    price:18000 ,
    location: "Ubud ",
    country: " Indonesia",
    categories:'Pools',
  },{
    title: "Santorini Pool Suites ",
    description:"  Cliffside suites with private pools and panoramic views of the Aegean Sea.",
    image: {
      filename:"Image",
      url: "  https://www.hotelswithprivatepool.com/Images/hotels-private-pool-santorini-dreams-luxury-suites.jpg",
    },
    price: 22000,
    location: "Santorini ",
    country: " Greece",
    categories:'Pools',
  },{
    title: "  Caribbean Beachfront Resort",
    description:"  A luxury resort with multiple pools and direct beach access in the Caribbean",
    image: {
      filename:"Image",
      url: "https://www.hotelswithprivatepool.com/Images/hotels-private-pool-santorini-filotera-suites5.jpg  ",
    },
    price: 20000  ,
    location: "Jamaica ",
    country: " Jamaica",
    categories:'Pools',
  },{
    title: "Dubai Skyline Pool Hotel ",
    description:" A modern hotel with a rooftop pool offering panoramic views of Dubai’s skyline. ",
    image: {
      filename:"Image",
      url: "  https://www.therooftopguide.com/rooftop-pools/Bilder/dubai-rooftop-pool-hero-2.jpg",
    },
    price: 21000 ,
    location: "Dubai ",
    country: " UAE",
    categories:'Pools',
  },{
    title: "Maldives Overwater Pool Bungalows ",
    description:"Luxurious overwater bungalows with private pools and direct access to crystal-clear waters.",
    image: {
      filename:"Image",
      url: " https://www.journeyera.com/wp-content/uploads/2022/01/Best-Resorts-Maldives-Couples-1200x800.jpg ",
    },
    price: 30000,
    location: "Maldives ",
    country: " Maldives",
    categories:'Pools',
  },
  { title: "Grand City Hotel",
     description: "A luxurious hotel in the heart of the city, offering stunning views and top-notch amenities.",
     image: {
          filename:"Image",
          url: " https://pix8.agoda.net/hotelImages/297246/-1/17c2453befa31fbf869116c3a1c676ef.jpg?ca=7&ce=1&s=375x",
        },

      price: 1200,
       location: "Mumbai",
        country: "India",
      categories: "City" },
  { title: "Castle Retreat", 
    description: "Experience royalty in this historic castle with modern comforts and spectacular surroundings.",
    image: {
      filename:"Image",
      url: "https://604now.com/wp-content/uploads/2021/10/castle-retreat.jpeg ",
    },
     price: 5000,
      location: "Rajasthan", 
      country: "India",
       categories: "Castles" },

  { title: "Mountain Camping Grounds",
     description: "Enjoy a rustic camping experience surrounded by breathtaking mountain views and serene nature.",
     image: {
      filename:"Image",
      url: " https://traveltmi.net/wp-content/uploads/2020/01/gongga-snow-mountain-2411069_1920.jpg",
    },
      price: 800,
       location: "Himachal Pradesh",
        country: "India", 
        categories: "Camping" },
  { title: "Farm Stay Lodge", 
    description: "Relax on a traditional farm stay with fresh produce and a peaceful countryside setting.", 
    image: {
      filename:"Image",
      url: "https://www.farmstayplanet.com/wp-content/uploads/2017/11/18134_gal_1_018728100_1452230887.jpg ",
    },
    price: 1500, 
    location: "Karnataka",
     country: "India",
      categories: "Farms" },
  { title: "Arctic Explorer Inn", 
    description: "An adventure stay in the Arctic region with unique accommodations and incredible natural phenomena.", 
    image: {
      filename:"Image",
      url: " https://r.profitroom.com/wildernesshotelnellim1/images/offers/thumbs/768x1024/zrrr7uLMWqedNwhk.JPG",
    },
    price: 7000, 
    location: "Svalbard",
     country: "Norway",
      categories: "Arctic" },
  { title: "Luxury Boat Hotel",
     description: "Stay on a luxury boat with beautiful ocean views and unparalleled comfort.",
     image: {
      filename:"Image",
      url: "https://luxurytravelinasia.com/wp-content/uploads/2014/12/rsz_aqua-mekong-exterior-evening-view-low-resolution-1.jpg ",
    },
      price: 6000,
       location: "Goa", 
       country: "India",
        categories: "Boats" },
  { title: "Elegant Rooms", 
    description: "Modern and stylish rooms in a central location, ideal for both business and leisure travelers.",
    image: {
      filename:"Image",
      url: "https://i.pinimg.com/originals/c3/82/70/c38270ee17d1901a31a1f26454700c2e.png ",
    },
    price: 1800, 
    location: "Delhi",
     country: "India",
      categories: "Rooms" },
  { title: "Dome Retreat", 
    description: "Stay in a cozy dome with panoramic views of the surrounding landscape, perfect for stargazing.",
    image: {
      filename:"Image",
      url: " https://inhabitat.com/wp-content/blogs.dir/1/files/2018/01/ecocamppatagonia6-889x711.jpg",
    },
     price: 2000,
      location: "Uttarakhand", 
      country: "India",
       categories: "Domes" },
  { title: "Beachside Villa", 
    description: "A beachfront villa with direct access to the sand and spectacular ocean views.",
    image: {
      filename:"Image",
      url: " https://h7c9z5u4.rocketcdn.me/wp-content/uploads/elementor/thumbs/photo-hd-real-estate-phuket-top-deluxe-sea-view-villa-for-sale-in-layan--q0a3sox6cgh9wn81vn4egd5ssld81vd2jl93ao2gmk.jpg",
    },
     price: 3500,
      location: "Kochi", 
      country: "India",
       categories: "City" },
  { title: "Royal Castle Stay",
     description: "Immerse yourself in history with this elegant castle accommodation featuring regal furnishings.",
     image: {
      filename:"Image",
      url: " https://jaipuragradelhitours.com/wp-content/uploads/2022/03/1.png",
    },
      price: 5500
      , location: "Punjab",
       country: "India", 
       categories: "Castles" },
  { title: "Forest Campgrounds",
     description: "Enjoy a secluded camping experience surrounded by lush forest and wildlife.", 
     image: {
      filename:"Image",
      url: "https://cdn.shortpixel.ai/spai/q_lossless+w_1435+to_webp+ret_img/mynorth.com/wp-content/uploads/2011/09/RS7988_CAMP-tent-hpr.jpg ",
    },
     price: 900, 
     location: "Kerala",
      country: "India", 
      categories: "Camping" },
  { title: "Countryside Farmhouse",
     description: "A charming farmhouse stay with organic farming activities and scenic views.",
     image: {
      filename:"Image",
      url: "https://cdn.onekindesign.com/wp-content/uploads/2020/01/Country-Modern-Farmhouse-Fletcher-Development-01-1-Kindesign.jpg ",
    },
      price: 1600
      , location: "Maharashtra", 
      country: "India", 
      categories: "Farms" },
  { title: "Glacier Lodge", 
    description: "Experience the beauty of glaciers with comfortable lodgings and guided tours.",
    image: {
      filename:"Image",
      url: " https://www.glacier-national-park-travel-guide.com/wp-content/uploads/2013/02/many-glacier-lodge-mountains2.jpg",
    },
     price: 7200,
      location: "Iceland",
       country: "Iceland", 
       categories: "Arctic" },
  { title: "Floating Luxury Suites", 
    description: "Luxurious suites on a floating platform offering panoramic views of the sea.",
    image: {
      filename:"Image",
      url: "https://luxurylaunches.com/wp-content/uploads/2015/05/qatar-is-building-an-octopus-shaped-floating-luxury-hotel-2.jpg ",
    },
     price: 6200,
      location: "Kerala", 
      country: "India", 
      categories: "Boats" },
  { title: "Business Hotel Suites",
     description: "Upscale suites with business amenities and easy access to city attractions.", 
     image: {
      filename:"Image",
      url: " https://pix8.agoda.net/hotelImages/364817/-1/8d9488b35bdcf2bc53cceda0fa6708c6.jpg?ce=0&s=800x",
    },
     price: 2000,
      location: "Bangalore", 
      country: "India", 
      categories: "Rooms" },
  { title: "Sky Dome Getaway",
     description: "A unique dome accommodation offering breathtaking views and cozy interiors.",
     image: {
      filename:"Image",
      url: " https://media.glampinghub.com/CACHE/images/accommodations/glamping-dome-romantic-getaways-near-austin-0-glamping-815133d4-ef5d-4643-9738-58321de85db8/943ad50160475d91c9e91dfd39f90e53.jpg",
    },
      price: 2200
      , location: "Himachal Pradesh",
       country: "India",
        categories: "Domes" },
  { title: "Downtown Luxury Hotel",
     description: "A high-end hotel in the city center with premium services and amenities.",
     image: {
      filename:"Image",
      url: " https://cdn.kiwicollection.com/media/property/PR008759/xl/008759-05-Mandarin%20Oriental%20Paris%20Exterior%20View.jpg?cb=1675729153",
    },
      price: 1300,
       location: "Chennai",
        country: "India",
         categories: "City" },
  { title: "Medieval Castle Hotel", 
    description: "Stay in a castle with medieval charm and modern comfort in a historical setting.", 
    image: {
      filename:"Image",
      url: "https://www.jetsetmag.com/wp-content/uploads/2014/10/k2_items_src_655cf7f08254436b1df6b279ffc38784.jpg ",
    },
    price: 5300, 
    location: "Uttarakhand",
     country: "India",
      categories: "Castles" },
  { title: "Desert Camp", 
    description: "Experience the thrill of desert camping with comfortable tents and local cuisine.", 
    image: {
      filename:"Image",
      url: " https://cf.bstatic.com/xdata/images/hotel/max1280x900/590918918.jpg?k=0ec9afed0b17b495186a0fc29c71287e02b4a4b8258e6cd567fb654ff74b0355&o=&hp=1",
    },
    price: 950, 
    location: "Rajasthan", 
    country: "India", 
    categories: "Camping" },
  { title: "Organic Farm Stay", 
    description: "A sustainable farm stay with hands-on farming experiences and healthy meals.",
    image: {
      filename:"Image",
      url: " https://www.keralatourism.org/responsible-tourism/uploads/urp/sup-doc/agri-unit-20230619093743551856.jpg",
    },
     price: 1400,
      location: "Goa", 
      country: "India", 
      categories: "Farms" },
  { title: "Northern Lights Lodge",
     description: "A lodge in a prime location to view the stunning Northern Lights and enjoy winter activities.",
     image: {
       filename:"Image",
       url: " https://www.wiredforadventure.com/wp-content/uploads/2018/11/Tromso-Credit-Bård-Løken-Visitnorway.com_-1.jpeg",
     },
      price: 7500,
       location: "Norway",
        country: "Norway",
         categories: "Arctic" },
  { title: "Luxury Yacht Hotel",
     description: "A top-tier yacht offering luxury accommodations and exclusive experiences on the water.", 
     image: {
       filename:"Image",
       url: "https://luxuryyachtgibraltar.hotelmix.co.uk/data/Photos/1920x1080/15847/1584700/1584700899/Luxury-Yacht-Hotel-Gibraltar-Exterior.JPEG ",
     },
     price: 6500, 
     location: "Goa", 
     country: "India",
      categories: "Boats" },
  { title: "Elegant Business Rooms", 
    description: "Sophisticated rooms designed for business travelers with all essential amenities.",
    image: {
      filename:"Image",
      url: "https://grandpalaceriga.com/wp-content/uploads/2019/10/Junior-Suite_1.jpg ",
    },
     price: 1900, 
     location: "Hyderabad", 
     country: "India",
      categories: "Rooms" },
  { title: "Starry Dome Retreat", 
    description: "A dome accommodation with clear skylights for stargazing and peaceful nights.", 
    image: {
      filename:"Image",
      url: "https://assets.atdw-online.com.au/images/15ece9336ee248492528983755e052e5.jpeg?rect=394%2C0%2C6297%2C4723&w=745&h=559&&rot=360&q=eyJ0eXBlIjoibGlzdGluZyIsImxpc3RpbmdJZCI6IjYzMWZjMzc4ODM3MzBjMjUwZmEwMzBiYyIsImRpc3RyaWJ1dG9ySWQiOiI1NmIxZWI5MzQ0ZmVjYTNkZjJlMzIwYzgiLCJhcGlrZXlJZCI6IjU2YjFlZTU5MGNmMjEzYWQyMGRjNTgxOSJ9 ",
    },
    price: 2100,
     location: "Rishikesh",
      country: "India", 
      categories: "Domes" },
  { title: "Urban Boutique Hotel",
     description: "A chic boutique hotel with stylish rooms and convenient access to city attractions.",
     image: {
       filename:"Image",
       url: " https://cf.bstatic.com/xdata/images/hotel/max1280x900/571388731.jpg?k=2cef4f2d2b6a42bf610e678b295a6be0b959229829983b2641a9db249a5390a9&o=&hp=1",
     },
      price: 1400,
       location: "Pune", 
       country: "India",
        categories: "City" },
  { title: "Luxurious Castle Hotel", 
    description: "Indulge in opulence with a stay in a luxurious castle with historical charm.",
    image: {
      filename:"Image",
      url: " https://www.inishview.com/wp-content/uploads/2023/04/lough-eske-castle-hotel-1-1536x1152.jpg",
    },
     price: 5400, 
     location: "Jaipur",
      country: "India", 
      categories: "Castles" },
  { title: "Mountain Retreat Campsite", 
    description: "A peaceful campsite in the mountains with breathtaking scenery and fresh air.", 
    image: {
      filename:"Image",
      url: "https://www.getaway.co.za/wp-content/uploads/2023/04/image7-719x431.jpeg ",
    },
    price: 850,
     location: "Sikkim",
      country: "India", 
      categories: "Camping" },
  { title: "Traditional Farm Stay",
     description: "Enjoy a traditional farm experience with authentic meals and scenic landscapes.", 
     image: {
       filename:"Image",
       url: "https://s1.it.atcdn.net/wp-content/uploads/2024/03/AhsaFarmstay_Exterior-1-315x236.jpg ",
     },
     price: 1550,
      location: "Uttar Pradesh", 
      country: "India", 
      categories: "Farms" },
  { title: "Snowy Peaks Lodge", 
    description: "A cozy lodge in the snow-capped peaks, ideal for winter sports and relaxation.",
    image: {
      filename:"Image",
      url: "https://www.panoramaresort.com/assets/Lodging/1000-Peaks/Peaks_2__FocusFillWzE4MDAsMTA4MCwieSIsNjBd.jpg ",
    },
     price: 7100,
      location: "Switzerland",
       country: "Switzerland", 
       categories: "Arctic" },
  { title: "Oceanfront Luxury Boat",
     description: "A luxury boat with oceanfront views, offering a unique and exclusive stay.", 
     image: {
       filename:"Image",
       url: " https://rokerhotel.co.uk/wp-content/uploads/2020/10/Executive_Double_Room_Gallery_6.jpeg",
     },
     price: 6300,
      location: "Andaman",
       country: "India",
        categories: "Boats" },
  { title: "Modern Executive Rooms",
     description: "Contemporary rooms equipped with amenities for business professionals.",
     image: {
       filename:"Image",
       url: " https://balajiinn.com/wp-content/uploads/2018/03/balaji-inn-executive-room-feature-image.jpg",
     },
      price: 1700,
       location: "Chandigarh",
        country: "India",
         categories: "Rooms" },
  { title: "Glamping Dome Retreat",
     description: "Glamorous camping in a dome with luxury features and beautiful surroundings.",
     image: {
       filename:"Image",
       url: " https://www.glampingdomestore.com/cdn/shop/products/20201206_145343_900x.jpg?v=1644105905",
     },
      price: 2300,
       location: "Darjeeling",
        country: "India",
         categories: "Domes" },
  { title: "Central Business Hotel",
     description: "A hotel centrally located for business travelers, with modern facilities and services.", 
     image: {
       filename:"Image",
       url: " https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/4a/7a/54/continental-hotel.jpg?w=1800&h=-1&s=1",
     },
     price: 1250, 
     location: "Ahmedabad", 
     country: "India", 
     categories: "City" },
  { title: "Luxurious Castle Stay",
     description: "Stay in a luxurious castle with modern amenities and historical charm.", 
     image: {
       filename:"Image",
       url: " https://relocatingtoireland.com/wp-content/uploads/Dromoland-Castle-1.jpg",
     },
     price: 5200, 
     location: "Madhya Pradesh",
      country: "India",
       categories: "Castles" },
  { title: "Eco-Friendly Camping", 
    description: "An eco-friendly camping experience with minimal environmental impact.", 
    image: {
      filename:"Image",
      url: " https://mendooutdoors.com/wp-content/uploads/2023/10/camping-preparation.jpg",
    },
    price: 880, 
    location: "Himachal Pradesh", 
    country: "India",
     categories: "Camping" },
  { title: "Heritage Farmhouse", 
    description: "Stay in a heritage farmhouse with traditional décor and local activities.",
    image: {
      filename:"Image",
      url: " https://www.realestate.com.au/news-image/w_1000,h_563/v1695218416/news-lifestyle-content-assets/wp-content/production/capi_e72245d743bac66df1a3e3196d750e40_0b74e9dc7669ad85c6069c17b9867420.webp?_i=AA",
    },
     price: 1650,
      location: "Haryana",
       country: "India",
        categories: "Farms" },
  { title: "Ice Hotel", 
    description: "A unique stay in an ice hotel with igloos and ice sculptures.",
    image: {
      filename:"Image",
      url: "https://www.thecuriouscreature.com/wp-content/uploads/2019/01/Ice-hotel-chandelier-1024x731.jpg ",
    },
     price: 7400, 
     location: "Sweden", 
     country: "Sweden", 
     categories: "Arctic" },
  { title: "Luxury Catamaran Hotel",
     description: "Enjoy luxury accommodations on a spacious catamaran with exceptional service.",
     image: {
       filename:"Image",
       url: " https://www.allatsea.net/wp-content/uploads/2023/05/Nomada-at-Sea-3.jpg",
     },
      price: 6400, 
      location: "Lakshadweep",
       country: "India",
        categories: "Boats" },
  { title: "Business Class Suites",
     description: "Elegant suites with all necessary amenities for business travelers.",
     image: {
       filename:"Image",
       url: " https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSW34ZRSHQ35bHMLDVzPbsNgwOlRxWQMj-vEw&s",
     },
      price: 1750, 
      location: "Gurgaon",
       country: "India", 
       categories: "Rooms" },
  { title: "Mountain Dome Stay", 
    image: {
      filename:"Image",
      url: "https://inhabitat.com/wp-content/blogs.dir/1/files/2018/01/ecocamppatagonia11-660x440.jpg ",
    },
    description: "A comfortable dome stay with stunning mountain views and cozy interiors.",
     price: 2150,
      location: "Shimla", 
      country: "India", 
      categories: "Domes" },
  { title: "Urban Luxury Hotel",
    description: "A luxury hotel offering a blend of modern amenities and city convenience.", 
    image: {
      filename:"Image",
      url: "https://static.travelgay.com/media/30505/responsive-images/The-Westin-Palace-Madrid___original_250_188.webp ",
    },
    price: 1450,
     location: "Bhubaneswar", 
     country: "India",
      categories: "City" },
  { title: "Castle Manor",
    description: "A manor-style castle offering grandeur and historical charm.", 
    image: {
      filename:"Image",
      url: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2a/15/95/10/the-castle-manor-inn.jpg?w=1400&h=-1&s=1 ",
    },
    price: 5600,
     location: "Jaisalmer", 
     country: "India", 
     categories: "Castles" },
  { title: "Highland Campsite", 
    description: "A campsite in the highlands with breathtaking views and fresh air.", 
    image: {
      filename:"Image",
      url: "https://www.caminoadventures.com/wp-content/uploads/2023/05/drymen-camping-west-highland-way-1200x675.jpg ",
    },
    price: 900, 
    location: "Leh",
     country: "India",
      categories: "Camping" },
  { title: "Rustic Farm Stay",
     description: "Experience rustic farm living with a focus on local produce and traditions.", 
     image: {
       filename:"Image",
       url: " https://cf.bstatic.com/xdata/images/hotel/square600/84789312.jpg?k=d6b3ce828099cd0cacc43c72547d98fd9ece552b41022772cbcd214f280cb3f1&o=",
     },
     price: 1500,
     location: "Goa"
     , country: "India",
      categories: "Farms" },
  { title: "Glacial Lodge",
     description: "Comfortable lodge with views of majestic glaciers and local tours.",
     image: {
       filename:"Image",
       url: " https://res.cloudinary.com/whistler/image/upload/w_900,c_scale,f_auto,dpr_2.0,q_auto/v1/s3/images/suppliers/summer/1307369/1.jpg",
     },
      price: 7300,
       location: "Greenland", 
       country: "Greenland",
        categories: "Arctic" },
  { title: "Exclusive Yacht Stay",
     description: "An exclusive stay on a luxury yacht with personalized services and stunning views.", 
     image: {
       filename:"Image",
       url: "https://www.charterworld.com/images/800/yachts-1/%5BMYDESTINATION-FOX-HARBR-TOO%5D-1512-1.jpg ",
     },
     price: 6600, 
     location: "Kochi",
      country: "India",
       categories: "Boats" },
  { title: "Executive Business Rooms", 
    description: "Business rooms equipped with high-end amenities and services.",
    image: {
      filename:"Image",
      url: " https://www.tridenthotels.com/-/media/trident-hotel/trident-gurgaon/Rooms--Suites/room-detail/Executive-Suite/banner1920x1080.jpg",
    },
     price: 1850, 
     location: "Noida",
      country: "India",
       categories: "Rooms" },
  { title: "Stargazing Dome", 
    description: "A dome stay with an emphasis on stargazing and comfort.",
    image: {
      filename:"Image",
      url: " https://www.travelandleisure.com/thmb/op2vgM_9jSba7P9dMAXwjnj5wf8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc()/clear-sky-resorts-grand-canyon-dome-interior-DOME0321-9f40c91b381d4ba0a89a9cf727dc4069.jpg",
    },
     price: 2250, 
     location: "Mussoorie", 
     country: "India", 
     categories: "Domes" },
  { title: "City Luxury Inn", 
    description: "Luxury accommodations in the city with premium services and amenities.",
    image: {
      filename:"Image",
      url: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/9d/a8/28/trump-soho-new-york.jpg?w=600&h=600&s=1 ",
    },
     price: 1350, 
     location: "Surat", 
     country: "India", 
     categories: "City" },
    { 
      title: "Skyline Towers", 
      description: "A modern hotel with breathtaking views of the city's iconic skyline.", 
      image: {
        filename:"Image",
        url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Palais_royale_worli_mumbai.png/320px-Palais_royale_worli_mumbai.png"
      },
      price: 1600, 
      location: "Mumbai", 
      country: "India", 
      categories: "City" 
    },
  
    { 
      title: "Historic Plaza Hotel", 
      description: "Stay in a historic plaza hotel that reflects the city's rich cultural heritage.", 
      image: {
        filename:"Image",
        url: "https://untappedcities.com/wp-content/uploads/2015/07/The-Plaza-Hotel-Central-Park-Fifth-Avenue-Exterior-NYC-2.jpg"
      },
      price: 1700, 
      location: "Delhi", 
      country: "India", 
      categories: "City" 
    },
  
    { 
      title: "Riverside Grandeur", 
      description: "Luxurious riverside accommodations offering stunning views and city landmarks.", 
      image: {
        filename:"Image",
        url: "https://www.theroyalganges.com/wp-content/uploads/2024/06/Longest-Riverside-Bungalow-in-Kolkata.png"
      },
      price: 1800, 
      location: "Kolkata", 
      country: "India", 
      categories: "City" 
    },
  
    { 
      title: "Golden Heritage Hotel", 
      description: "Experience opulence in this hotel located in the heart of the city’s historic district.", 
      image: {
        filename:"Image",
        url: "https://pix8.agoda.net/hotelImages/227/2276807/2276807_17052317030053169207.jpg?ca=6&ce=1&s=1024x"
      },
      price: 1900, 
      location: "Jaipur", 
      country: "India", 
      categories: "City" 
    },
  
    { 
      title: "Majestic Skyline Suites", 
      description: "Exclusive suites with panoramic views of the city's iconic skyline and landmarks.", 
      image: {
        filename:"Image",
        url: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/e7/04/f9/majestic-city-retreat.jpg?w=1400&h=-1&s=1"
      },
      price: 2000, 
      location: "Bangalore", 
      country: "India", 
      categories: "City" 
    }
  
];


module.exports = { data: sampleListings };