# Exported from Render on 2024-09-13T08:38:03Z
services:
- type: web
  name: CompassBooking
  runtime: node
  repo: https://github.com/aniketchauhan01/MajorProject
  plan: free
  envVars:
  - key: SECRET
    sync: false
  - key: ATLASDB_URL
    sync: false
  - key: CLOUD_API_SECRET
    sync: false
  - key: CLOUD_API_KEY
    sync: false
  - key: CLOUD_NAME
    sync: false
  region: oregon
  buildCommand: npm install
  startCommand: node index.js
version: "1"
